Cleaning client code
netgroup-polito/CrownLabs pull request #308
Opened 2020-09-20 13:01 UTC by GabriFila

# Description

This PR includes some cleaning and changes to the client code, mostly to UserLogic.jsx. This is done to reduce the complexity of the code and ease readability. This PR will be followed by others to clean the code, I prefer to avoid a single big PR to allow for better code reviewing and reduce bug passing.

Main changes:
- the info about the selected instance is no longer used, the data is provided by the calling function from the UI
- the UI doesn't use events so I removed the code, it is still on git in case we need it
- adminHidden was a bit confusing so I changed it to isStudentView

### ***Important***
Do you think we should squash the commit before merging them? I added the `hold` label to wait for your answer

# How Has This Been Tested?

This has been tested by checking that all the required functionalities still performed the same way as before:
- view templates and instances running
- start an instance
- connect to an instance
- stop an instance
- create a template
- delete a template

2020-09-21 07:35 UTC, giorio94 requested changes
Great @GabriFila! The new names are much more user-friendly

Just a couple of issues I discovered while testing the UI:
1. The list of Running Labs disappears if the page is reloaded
2. The professor view does no longer display the owner the VM
3. It is not possible to delete VMs from the professor view (see the specific comment)

From my point of view, multiple commits are perfectly fine, since each one addresses a separate issue.

2020-09-21 07:35 UTC, giorio94 commented on webservice/src/UserLogic.jsx
> +        instanceLabsAdmin.get(instanceName).studNamespace
Here the `studNamespace` property is used, but it is no longer set. Hence, the deletion of a laboratory from the professor view fails.

2020-09-21 23:50 UTC, s41m0n approved these changes

2020-09-22 21:20 UTC, GabriFila commented
> Great @GabriFila! The new names are much more user-friendly
> 
> Just a couple of issues I discovered while testing the UI:
> 
> 1. The list of Running Labs disappears if the page is reloaded
> 2. The professor view does no longer display the owner the VM
> 3. It is not possible to delete VMs from the professor view (see the specific comment)
> 
> From my point of view, multiple commits are perfectly fine, since each one addresses a separate issue.

Thanks for the review, regarding your points:
1. the list disappears for an issue related to the k8s watcher and some browser, in the future it could be fixed by not using the watcher if it fails
2. Fixed it in the last commit, also added capability to sort and filter by user
3. You are right, now it should be fixed

2020-09-22 21:20 UTC, GabriFila commented
/rebase

2020-09-23 06:47 UTC, giorio94 approved these changes
Thanks @GabriFila 

/approve

2020-09-23 06:48 UTC, merged